### ISSUE TITLE
[enhancement] Indicate a cycle is active

### ISSUE THREAD

**Issue by hugalafutro** [MapoDan/home-assistant#1]
Hi,
I really like the new min_cycle_duration setting, but sometimes I forget about it and fiddle about with the temperature and wonder why it's not switching the heater on/off. 

I think an indicator on the ha card that a cycle is currently active (and maybe the time left on the cycle) would be useful.

**Comment by MapoDan** [comment]
Ciao
I'm not able to develop cards, so the only things that I could do is to expose a custom attribute with this information.
Anyway I don't have enough time to dedicate to programmable thermostat except to fix breaking changes in HA.

You can open a PR to add this.
In anycase I close this since this issue should have been open on the component page.
